/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "addNote",
            "endpoint": "https://abbo5ja467.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        },
        {
            "name": "notesLAMBDA",
            "endpoint": "https://ietfqzvyre.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://fb443xz5dnaq7jqpmplfh4wbie.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-zqawya4bgvdb3dfnlvm7nhjqwm",
    "aws_cognito_identity_pool_id": "us-east-1:22ff2145-5d49-496e-9c28-3c67a1049ece",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_jnYNfsA5H",
    "aws_user_pools_web_client_id": "431adoag6g6cr4tiu1m3sua7t7",
    "oauth": {
        "domain": "assignment154525b5d-54525b5d-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:5173/",
        "redirectSignOut": "http://localhost:5173/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "notes200134-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "notesUserInfo-dev",
            "region": "us-east-1"
        },
        {
            "tableName": "notesapp-dev",
            "region": "us-east-1"
        }
    ],
    "aws_mobile_analytics_app_id": "0ee34f13585c4af68e35f573b7f0b6eb",
    "aws_mobile_analytics_app_region": "us-east-1",
    "Analytics": {
        "AWSPinpoint": {
            "appId": "0ee34f13585c4af68e35f573b7f0b6eb",
            "region": "us-east-1"
        }
    },
    "Notifications": {
        "Email": {
            "AWSPinpoint": {
                "appId": "0ee34f13585c4af68e35f573b7f0b6eb",
                "region": "us-east-1"
            }
        }
    }
};


export default awsmobile;
